### ISSUE TITLE
Type Error in alpdesk/alpdesk-parallax/src/Listener/HooksListener.php Line 48

### ISSUE THREAD

**Issue by arboc** [xprojects-de/alpdesk-parallax#32]
$this->requestStack->getCurrentRequest() can be type of Request or null.

if $this->requestStack->getCurrentRequest() is null than this results into an type error

``` 
"Contao\CoreBundle\Routing\ScopeMatcher::isFrontendRequest(): Argument #1 ($request) must be of type Symfony\Component\HttpFoundation\Request, null given, called in vendor/alpdesk/alpdesk-parallax/src/Listener/HooksListener.php on line 48"
```

**Comment by arboc** [comment]
I will send a merge request to solve this

**Comment by xprojects-de** [comment]
@arboc 
Can you explain exactly how the error occurs? In the hook, the request should not actually be null!

**Comment by xprojects-de** [comment]
Since Contao 5.4 the request-Variable can also be null

https://github.com/contao/contao/blob/1641c8388c3792daba0d2214a2152357b1531b1f/core-bundle/src/Routing/ScopeMatcher.php#L59

In 5.3 it must be of Type Request
https://github.com/contao/contao/blob/a262bd18a4a334076f1d6f911932859fa8b1bc86/core-bundle/src/Routing/ScopeMatcher.php#L55

That´s the reason for the error. So maybe we have to fix it.

But I would still like to understand why the request is null ...

**Comment by arboc** [comment]
Contao 4.13   
PHP 8.3  

with terminal42/contao-news_newsletter and notification center v1.  
When we send a news as e newsletter we get the error explained above.

**Comment by arboc** [comment]
and we are using the mailing queue.  
the queue is processed by a PHP CLI... that's why the request is null
